[project]
name = "project2-newsference"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "lxml-html-clean>=0.4.1",
    "newsapi-python>=0.2.7",
    "newspaper3k>=0.2.8",
    "openai>=1.61.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
